site_name: tw-gaffer-jta Documentation
repo_url: https://github.com/transferwise/tw-gaffer-jta
edit_uri: blob/master/docs/
nav:
  - Overview: index.md
  - Usage: usage.md
  - Contributing: contributing.md